<!doctype html>
<html class="no-js" lang="en">
  <head>
    <?php
        // common head meta tags
        echo $this->partial('includes/head.phtml') ?>

    <?php
        // common stylesheets
        echo $this->partial('assets/stylesheet.phtml') ?>

    <?php
        // specific stylesheets for this layout
        echo $this->partial('site/assets/stylesheet.phtml') ?>
  </head>
  <body class="<?php printf('env-%s mod-%s', APPLICATION_ENV, Zend_Controller_Front::getInstance()->getRequest()->getParam('module')) ?>">
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong>
          browser. Please <a href="http://browsehappy.com/">upgrade your browser</a>
          to improve your experience.
        </p>
    <![endif]-->

    <?php
        // specific header/navigation for this layout
        echo $this->partial('site/header.phtml') ?>

    <?php
        // ZF's main site content
        echo $this->layout()->content ?>

    <?php
        // specific header/navigation for this layout
        echo $this->partial('site/footer.phtml') ?>

    <?php
        // common javascript
        echo $this->partial('assets/javascript.phtml') ?>

    <?php
        // specific javascript for this layout
        echo $this->partial('site/assets/javascript.phtml') ?>
  </body>
</html>
